### ISSUE TITLE
ตาม มคอ2 ในเวบ tqf.up.ac.th

### ISSUE THREAD

**Issue by pchaow** [SEUP/Mainboard#11]
ติดตามผล มคอ 2 หลักสูตร 2560 จากเว็บ tqf.up.ac.th

**Comment by chontipan** [comment]
ตอนนี้นำเข้าวิชา 235 ได้ครบแล้ว ตอนนี้เหลือแต่หน่วยกิตรวมจาก 129 ให้เป็น 128 (1)

**Comment by chontipan** [comment]
add วิชา 235091 และตั้งเป็นไม่นับหน่วยกิตได้เเล้ว แต่จำนวนหน่วยกิตรวมยัง 129 ไม่เป็น 128(1) ไว้จะลองถามพี่จ๋อมแจ๋มอีกที

**Comment by chontipan** [comment]
กดส่งแบบละครับ คุณเอี่ยวให้ใส่เลข 0 ในช่องหมวด 3.1 ตรง รายวิชาไม่นับหน่วยกิตก่อน
