### ISSUE TITLE
ดูงานวันที่ 28-29 กย

### ISSUE THREAD

**Issue by davitse** [SEUP/Mainboard#15]
พฤ บ่าย 20scoops
ศ เช้า nextzy

**Comment by pchaow** [comment]
คุณตอยแจ้งมาว่าจะได้ วันเสาร์เช้า
คงต้องหาศุกร์บ่ายอีกที่

**Comment by chontipan** [comment]
คุณตอยแจ้งมาว่า ตอนนี้ได้ติดต่อบริษัท nextzy และ thinknet ครับ และอาจจะไม่สะดวกวันเสาร์ 

แนวทางแก้ไข
อาจจะเปลี่ยนแผนเป็นเดินทางพฤหัสบดี โดยต้องไปเช็คตารางเรียนของนิสิตปีสี่

การดำเนินการ
- รอสรุปยอดคนไป โดยดราฟจะมาแจ้งปีสามว่าจะไปด้วยมั้ย?
