### ISSUE TITLE
ประชุมสาขาประเก็น กกน

### ISSUE THREAD

**Issue by noptanit12** [SEUP/Mainboard#17]
ประชุมสาขาประเด็น กกน
1. นิสิตดีเด่นด้านกิจกรรมเสริมหลักสูตร
2. นิสิตที่ได้รับรางวัลต่าง ๆ
3. นิสิตผลการเรียนดีเด่น

**Comment by davitse** [comment]
นิสิตที่ได้รับรางวัลต่างๆ 
เรียนดี 58023750 ธราทร  ตันวินิจ
