### ISSUE TITLE
ปรับคำอธิบายรายวิชา Data Structure and Algorithm

### ISSUE THREAD

**Issue by chontipan** [SEUP/Mainboard#19]
ปรับคำอธิบายรายวิชา Data Structure and Algorithm แยกออกเป็น
1. Concepts of Algorithms (แนวคิดของอัลกอริทึม)
2. ย้าย ส่วน Data Structure ไปรวมกับ Fundamental of Problem Solving and Programming II

link to #18

**Comment by pchaow** [comment]
227205	โครงสร้างข้อมูลและขั้นตอนวิธี		3(2-2-5)
   	        Data Structures and Algorithms
โครงสร้างข้อมูลขั้นพื้นฐาน อาร์เรย์ รายการแบบเชื่อมโยง สแตก คิว ต้นไม้ กราฟ 
การวิเคราะห์ประสิทธิภาพและความซับซ้อนของขั้นตอนวิธี การเรียงลำดับและการค้นหาข้อมูล การจัดเก็บข้อมูลแบบฮีพ แฮชชิ่ง การเวียนเกิด การประยุกต์ใช้โครงสร้างข้อมูลและขั้นตอนวิธี
Basic data structures, array, linked-listed, stack, queues, trees, graph, analysis of algorithm efficiency and complexity, sorting and searching, heap storage, hashing, recursion, application of data structures and algorithms

แก้เป็น
227205	แนวคิดของอัลกอริทึม		3(2-2-5)
   	        Concepts of Algorithms
ความสำคัญของอัลกอริทึมที่มีประสิทธิภาพ การวิเคราะห์ประสิทธิภาพและความซับซ้อนของขั้นตอนวิธี สัญลักษณ์แสดงขีดจำกัด การเรียงลำดับและการค้นหาข้อมูล อัลกอริทึมแบบแบ่งแยกและเอาชนะ อัลกอริทึมเชิงละโมบ การโปรแกรมแบบพลวัต ฮีพ แฮชชิ่ง การประยุกต์ใช้โครงสร้างข้อมูลและขั้นตอนวิธี
The importance of efficient algorithms, analysis of algorithm efficiency and complexity, asymptotic notation, sorting and searching, divide and conquer algorithms, greedy algorithms, dynamic programming, heap, hashing, application of data structures and algorithms

**Comment by pchaow** [comment]
แก้เป็น
227102   พื้นฐานการแก้ปัญหาและการเขียนโปรแกรม 2                    		3(2-2-5)
 Fundamental of Problem Solving and Programming II
             การทบทวนการเขียนโปรแกรมพื้นฐาน คำสั่งควบคุมแบบลำดับ คำสั่งควบคุมแบบทางเลือก คำสั่งควบคุมแบบทำซ้ำ ตัวแปรแถวลำดับ ฟังก์ชัน ฟังก์ชันเวียนเกิด มอดูลและไลบรารี การดำเนินการกับไฟล์ คลาสและโครงสร้างข้อมูล สแตก คิว ต้นไม้ กราฟ
Basic programming reviews, sequence control statement, selection control statement, repetition control statement, arrays, function, recursive function, modules and library, file operation,  class and data structures, stack, queues, trees, graph
