### ISSUE TITLE
จัดเตรียมโครงการสาขา อบรมการเขียนส่ง AUCC

### ISSUE THREAD

**Issue by chontipan** [SEUP/Mainboard#7]

**Comment by pchaow** [comment]
ขอรายการด้วยนะครับ ว่าต้องทำอะไรบ้าง

**Comment by chontipan** [comment]
1. ทำเรื่องขออนุมัติ + ดำเนินโครงการ
2. จองห้องอบรม
3. ทำเรื่องเชิญวิทยากร + ทำกำหนดการ (น่าจะช่วง 4-5 กพ. 60 เชิญ อ.ฟู อ.วิษ เป็น วิทยากร เพราะส่ง AUCC 20 กพ. 60)
4. แบบสอบถาม (เดวค่อยเมคเอา)
5. ถ่ายรูปวันงาน+ใบลายชื่อ
6. ทำสรุปส่งประกัน
